name = "Against the Storm"
home = "https://discord.com/channels/731205301247803413/1250491355290140672"
default_url = "https://github.com/Ryguy-9999/ArchipelagoATS/releases/download/v{{version}}/against_the_storm.apworld"

[versions]
"1.1.0" = {}
