name = "Buckshot Roulette"
home = "https://discord.com/channels/731205301247803413/1234399148665737237"
default_url = "https://github.com/asdfwyay/APBuckshot/releases/download/v{{version}}/buckshot.apworld"

[versions]

"0.0.3" = {}
"0.1.0" = {}
"0.1.1" = {}

