name = "ClusterTruck"
home = "https://discord.com/channels/731205301247803413/1344157838578290792"
default_url = https://github.com/Nullctipus/ArchipelagoClusterTruck/releases/tag/{{version}}/cluster_truck.apworld

[versions]
"1.3.1" = {}
