name = "Mega Man X Command Mission"
home = "https://discord.com/channels/731205301247803413/1329119629364170772"

[versions]
"0.1.0" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.0/commandmission.apworld" }
"0.1.1" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.1/commandmission.apworld" }
"0.1.2" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.2/commandmission.apworld" }
"0.1.3" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.3/commandmission.apworld" }
"0.1.4" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.4/commandmission.apworld" }
"0.1.5" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.5-CharacterUpdate/commandmission.apworld" }
"0.1.6" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.6/commandmission.apworld" }
"0.1.61" = { url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V0.1.61/commandmission.apworld" }
