name = "Mega Man X Command Mission"
home = "https://discord.com/channels/731205301247803413/1329119629364170772"
default_url = "https://github.com/themogulAP/ArchipelagoCM/releases/download/V{{version}}/commandmission.apworld"

[versions]
"0.1.61" = {}
