name = "Crash2"
display_name = "Crash Bandicoot 2"
home = "https://discord.com/channels/731205301247803413/1371461990794657863"
default_url = "https://github.com/Sim10XXX/C2AP/releases/download/v{{version}}/crash2.apworld"

[versions]
"0.2.0" = {}