name = "Castlevania: Dawn of Sorrow"
# The author has publicly expressed their hatred for this project and adjacent ones, going as far as expressing their will to find a way to get excluded from it. Respect their wish
disabled = true
