name = "DELTARUNE"
home = "https://discord.com/channels/731205301247803413/1169376681937612920"
default_url = "https://github.com/theemeraldsword85/DELTARUNEAP/releases/download/v{{version}}/deltarune.apworld"

[versions]
"0.2.7" = {}
