name = "Final Fantasy IV Free Enterprise"
home = "https://discord.com/channels/731205301247803413/1170144930610557008"

[versions]
"0.7.0" = { url = "https://github.com/Rosalie-A/Archipelago/releases/download/FFIV-AP-v7/ff4fe.apworld" }
