name = "Final Fantasy X"
home = "https://discord.com/channels/731205301247803413/1304953414148554824"
default_url = "https://github.com/FFX-AP/Archipelago/releases/download/v{{version}}/ffx.apworld"

[versions]
"0.2.1" = {}