name = "Lobotomy Corporation"
home = "https://discordapp.com/channels/1085716850370957462/1349105013783400529"
tags = ["ad"]

[versions]
"1.2.0" = { url = "https://github.com/Kli333/LobCorp-AP/releases/download/v1.2.0.0/lobotomycorporation.apworld" }
