name = "Manual_PrincessPeachShowtime_AliRobotnik"
display_name = "Manual: Princess Peach Showtime"
home = "https://github.com/AliRobotnik/Princess-Peach-Showtime-Archipelago-Manual"

[versions]
"1.2.0" = { url = "https://github.com/AliRobotnik/Princess-Peach-Showtime-Archipelago-Manual/releases/download/V1.2/manual_PrincessPeachShowtime_alirobotnik.apworld" }
"1.2.2" = { url = "https://github.com/AliRobotnik/Princess-Peach-Showtime-Archipelago-Manual/releases/download/V1.2.2/manual_princesspeachshowtime_alirobotnik.apworld" }
