name = "Manual_AceCombat7_Qairyl"
display_name = "Manual: Ace Combat 7"
home = "https://discord.com/channels/1097532591650910289/1454360452221108274"

[versions]
"0.0.1" = { local = "../apworlds/manual_acecombat7_qairyl.apworld" }
