name = "Manual_TheLordoftheRingsTheBattleforMiddleearthII_SaltySwords"
display_name = "Manual: The Lord of the Rings: The Battle for Middle-earth II"
home = "https://github.com/SaltySwords/Archipelago-BFME2-Manual/releases/download/v{{version}}/manual_thelordoftheringsthebattleformiddleearthii_saltyswords.apworld"

[versions]
"1.0.0" = {}
