name = "Manual_PlaytimewithPercy_WolfBoi008"
display_name = "Manual: Playtime with Percy"
home = "https://github.com/WolfBoi008/Playtime-with-Percy"
default_url = "https://github.com/WolfBoi008/Playtime-with-Percy/releases/download/{{version}}/manual_playtimewithpercy_wolfboi008.apworld"

[versions]
"1.2.1" = {}
