name = "Manual_MarvelRivals_SnolidIce"
display_name = "Manual: Marvel Rivals (Generic)"
home = "https://discord.com/channels/1097532591650910289/1314368372225474632"

[versions]
# https://discord.com/channels/1097532591650910289/1314368372225474632/1472722159821394112
"0.0.1" = { local = "../apworlds/manual_marvelrivals_snolidice-0.0.1.apworld" }
