name = "Manual_Cars_WolfBoi008"
display_name = "Manual: Cars"
home = "https://discord.com/channels/1097532591650910289/1402843300985176114"
default_url = "https://github.com/WolfBoi008/Cars/releases/download/{{version}}/manual_cars_wolfboi008.apworld"

[versions]
"1.2.1" = {}
