name = "Manual_SongbirdSymphony_MJB20077"
display_name = "Manual: Songbird Symphony"
home = "https://discord.com/channels/1097532591650910289/1444476490547859587"

[versions]
# https://discord.com/channels/1097532591650910289/1444476490547859587/1445496638570500229
"0.0.1" = { local = "../apworlds/manual_songbirdsymphony_mjb20077-0.0.1.apworld" }
