name = "Manual_XenobladeChroniclesv2_Xanderoni_skipperki1"
display_name = "Manual: Xenoblade Chronicles"
home = "https://discord.com/channels/1097532591650910289/1216897393019322388"
default_url = "https://github.com/Garfunkiel/Manual-XenobladeChronicles-Xanderoni/releases/download/{{version}}/manual_xenobladechroniclesv2_xanderoni_skipperki1.apworld"

[versions]
"2.0.5-garfunkiel" = {}