name = "Minecraft"
home = "https://discord.com/channels/731205301247803413/837136185662111746"
default_url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/{{version}}/minecraft.apworld"

[versions]
"0.1.7-hotfix" = {url = "https://github.com/jacobmix/Minecraft_AP_Randomizer/releases/download/0.1.7_hotfix/minecraft.apworld"}
