name = "Mario Kart 64"
home = "https://discord.com/channels/731205301247803413/1124649084544876615"

[versions]
"0.2.3" = { url = "https://github.com/Edsploration/MK64-Archipelago/releases/download/mk64%2F0.2.3/mk64.apworld" }
