name = "Majora's Mask Recompiled"
home = "https://discord.com/channels/731205301247803413/1368653154241089546"
default_url = "https://github.com/RecompRando/MMRecompRando/releases/download/v{{version}}/mm_recomp.apworld"

"0.9.5a" = { url = "https://github.com/RecompRando/MMRecompRando/releases/download/v0.9.5a/mm_recomp.apworld" }
