name = "Momodora Moonlit Farewell"
home = "https://discord.com/channels/731205301247803413/1351406749315240007"

[versions]
"1.7.5+1" = {url = "https://github.com/alditoOt/Momodora-Moonlit-Farewell-Randomizer/releases/download/AP-v.1.7.5.1/momodoramoonlitfarewell.apworld"}
