name = "Outer Wilds"
home = "https://discord.com/channels/731205301247803413/1462820272012005489"
default_url = "https://github.com/Ixrec/OuterWildsArchipelagoRandomizer/releases/download/v{{version}}/outer_wilds.apworld"

[versions]
"0.3.6" = {}
"0.3.9" = {}
"0.3.11" = {}
"0.3.12" = {}
"0.3.13" = {}
"0.3.14" = {}
"0.3.15" = {}
"0.3.16" = {}
"0.3.17" = {}
"0.3.18" = {}
"0.3.19" = {}
"1.0.1" = {}
"1.1.0" = {}
