name = "ShippedInSpace"
home = "https://github.com/Typ0Codes/shipped-in-space-archipeligo-support/tree/main"
default_url = "https://github.com/Typ0Codes/shipped-in-space-archipeligo-support/releases/download/{{version}}/shippedinspace.apworld" 

[versions]
"1.0.0" = {} #Orignal version
"2.0.0" = {} #Updated with actual logic instead of clique 40 times
