name = "Spelunky 2"
home = "https://discord.com/channels/731205301247803413/1142626744629735555"
default_url = "https://github.com/DDR-Khat/Spelunky2-Archipelago/releases/download/{{version}}/spelunky2.apworld"

[versions]
"0.3.5" = {}
"0.3.4" = {}
"0.3.3" = {}
"0.3.2" = {}
"0.3.1" = {}
"0.3.0" = {}
"0.2.4" = {}
