name = "Tevi"
home = "https://discord.com/channels/731205301247803413/1320015979736203304"
# Has a bug where it leaks state between different slots running the game
disabled = true

[versions]
"0.6.6" = { url = "https://github.com/BlackSoulKnight/Tevi_Randomizer/releases/download/v1.4.6/tevi.apworld" }
