name = "Void Sols"
home = "https://discord.com/channels/731205301247803413/1448045030777421844"

[versions]
"1.0.1" = {url = "https://github.com/cookie966507/Archipelago/releases/download/1.0.1-Void-Sols/void_sols.apworld"}
