name = "Void Stranger"
home = "https://discord.com/channels/731205301247803413/1231073014439743528"
default_url = "https://github.com/CriminalPancake/void-stranger-ap/raw/refs/tags/v{{version}}/voidstranger.apworld"
# This version is quite old, and the newer version has clear signs of self locking items which get hidden by the empty apworld
disabled = true


[versions]
"0.8.0" = {}
"0.8.4-hotfix1" = { url = "https://github.com/CriminalPancake/void-stranger-ap/raw/refs/tags/v0.8.4.1/voidstranger.apworld" }
"0.9.1" = { url = "https://github.com/CriminalPancake/void-stranger-ap/releases/download/v0.9.1.0/voidstranger.apworld" }
