name = "Yu-Gi-Oh! Dungeon Dice Monsters"
home = "https://discord.com/channels/731205301247803413/1298768685510561842"
default_url = "https://github.com/JustinMarshall98/Archipelago---YuGiOh-Dungeon-Dice-Monsters-GBA-/releases/download/v{{version}}/yugiohddm.apworld"

[versions]
"0.3.2" = {}
