[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_GrappleDog_ProfDeCube')"]]
__expected__ = "fail"
__version__ = ">=1.0.0"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_GrappleDog_ProfDeCube')"]]
__expected__ = "fail"
__version__ = ">=1.0.0"
