[["test.general.test_items.TestBase.test_item_name_group_conflict [Notes] (group_name='Notes', game_name='Manual_SongbirdSymphony_MJB20077')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_SongbirdSymphony_MJB20077', option='Example_Toggle')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_SongbirdSymphony_MJB20077', option='Example_Choice')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_SongbirdSymphony_MJB20077', option='Example_Range')"]]
__expected__ = "error"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_SongbirdSymphony_MJB20077', option='DLC_enabled')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
