[["test.general.test_locations.TestBase.test_location_group [Reverse Caverns] (group_name='Reverse Caverns', game_name='Symphony of the Night')"]]
__expected__ = "fail"
__version__ = ">=0.8.16+unofficial"
